= タイトル
* Jenkinsの紹介

== 前提
* 話す内容 +
Jenkinsについて紹介を行いたいと思いますが、現在のプロジェクトがJavaの開発を行っていることや +
JenkinsがJavaの開発で広く利用されていることから、今回はJavaの開発を前提としてJenkinsについて +
説明させていだだきます。 +
もちろんJenkinsはJavaだけでなく、Python、PHPといったJava以外の開発でも利用することができます。

== CI/CDとは
* 話す内容 +
Jenkinsについて説明するをするまえにCIについて知っていただく必要があるため、まずはCIについて説明を行います。 +
皆さん、CI（CD）が何かご存知でしょうか？ +
CIとはContinuouts Integrationの略で、一般的には継続的インテグレーションと呼ばれています。 +
サイクルの図を使う +
- コンパイル +
- 静的解析 +
- 単体テスト +
- デプロイ +
具体的には、開発者がGitやSVNなどのバージョン管理システムに対してソースコードの変更をコミットする度に、スライドで示すような +
ビルドを自動的に行うことを指します。ここでいうデプロイとは、静的解析の結果をSonarQubeのようなメトリクスツールにデプロイする　+
ことやNexusやartifactといったライブラリ管理にアーカイブしたjarファイルをデプロイすることを言います。 +

CIのメリットとして、変更内容をバージョン管理システムに対してコミットしたときにローカル環境で開発者が発見できていないミスを +
コミットの度にビルドが走るので発見することができます。 +
ミスが見つかるたびに修正を行うため、行程が進んだ後の手戻りの削減につながります。 +
人間による手作業ではなく自動でビルドを実行するので、稼働時間の短縮や品質の維持にもつながります。

== CIで利用できるって何があるの？
* 話す内容 +
先ほど説明したようなビルドを自動で実行するためのツールはいくつかありますが、ここではJenkins、CircleCI、TravisCIについて +
簡単に説明したいと思います。

この3つのCIツールをサービスの面で比較すると、Jenkinsはオンプレミスであり、残りのCircleCiとTravisCiはSaasです。 +
次に、GitHubと連携ができるかを比較した時に、3つのツールともGithubと連携することが可能です。 +
次に、WebGUIの設定ができるかを比較したときに、JenkinsとCircleCIはWebGUIによる設定することが可能ですが、 +
TravisCiに関しては、ファイルによって設定を行う必要があります。

== Jenkinsとは
* 話す内容
JenkinsとはCIで説明したビルドを自動で行うためのツールである。

=== Jenkinの起動方法
* jre環境があれば、java -jar jenkins.warで起動可能です
* tomcatにjenkins.war  +
いかに簡単に起動できるかを示すため、起動を図を使って説明する。 +

=== Jenkinsの説明(Jenkins1の内容)
* 話す内容 +
Jenkinsｍを利用するメリットはいくつかあります。 +
** 集合知がある（プラグイン）← 何個かプラグインの説明する？ +
Jenkinsには多くのプラグインが存在するため汎用性が高いです。また、書籍も出版されており +
ネットにも多くの情報が転がっているため、設定方法やエラー事象の解決方法を発見しやすいといったメリットがあります。
** GUIで設定可能 +
GUIの設定を画像を使って説明する。 +
Jenkinsのタスクを実行するための設定(ジョブ)はGUIベースで行うことができ、誰でも簡単に設定することができる。 +
** 定期実行可能 +
ビルドを行う時間を設定することが可能であるため、毎日行うビルドがあった場合、ビルド忘れをなくすことができ作業の手間を省くことにもつながります。
** ビルドの順番を操作することができる +


=== Jenkins2の説明
* 話す内容 +
ここまでに説明したメリットはJenkins1の情報であり、ご存知の方も多いのではないでしょうか？ +
Jenkins2では、大きく変わった点があります。

** pipeline機能が追加された +
Pipeline機能が追加されたことによりgitとの相性が良くなった。 +
Gitとの相性が良くなったというのはgitの機能に関連します。

*** gitについての説明 +
皆さん、そもそもGitを利用していますか？ +
まだ、ソースコード管理にSVNを利用していませんか？ +
SVNはもう時代遅れです。 +
https://blogs.oracle.com/ouchina/2016java のグラフを利用する←現状良いグラフが見つからない +
以上のグラフからも分かるように、ソースコード管理といえば今はgitです。

Gitの何が良いのかについて説明します。 +
Gitとは、SVNと同じソースコード管理システムの1つです。 +
ここで図を使う(SVNとGitの比較) +
SVNは基本的に、trunk、tag、branchの3つで構成されており、基本的には全員がトランクで作業を行い、ある作業時点のトランクの状態をタグを打ち判断できるようにし +
別の開発を行うときは、branchを切るといった流れです。開発者が作業する場所がtrunkしかないうえに、リポジトリが一つであり、変更を容易にコミットすることが +
できなかった。また、変更内容を記録するために場合によっては管理簿のようなものを用意する必要があった。 +
Gitは、masterとブランチから構成されており、開発者はmasterからブランチを複数切ることができ、ブランチごとに作業を分けることが可能となりました。また、リモートと +
ローカルにリポジトリを持っており、変更をSVNとはことなり容易にコミットできるようになりました。
最も大きな点としてはソースコード差分を見ることができ、それに対してレビューが行えるため、Gitだけで変更の管理を行えるようになりました。

SVNとGitの比較に関しては、もう少し調べる必要あり。

** 続き +
multibranchPipelineではブランチごとにジョブが実行され、Pipelineでは指定したブランチのみジョブが実行されます。 +

** ジョブの定義をファイルで行うことが可能となった +
Jenkins1を利用したことがある人はブランチがたくさんできるからその度にジョブを定義しなくてはいけないのではと思ったのではないでしょうか？ +
これを解決するのがJenkins2から導入されたJenkinsfileです。 +
Jenkinsfileはgroovyで書けるジョブを定義したファイルです。 +
このJenkinsfileをmasterに持たせておけば、ブランチを切る度にそのブランチにはJenkinsfileが存在するため、 +
わざわざブランチごとにジョブを作成する必要がなくなります。 +
また、ファイルでジョブ設定を管理できることになったことによって、バックアップをGUIで設定を変更の度に取らなくても良くなり、 +
バックアップができていなかった時にも、柔軟に対応することが可能となります。 +
また、ファイル管理できることで、複数の人が設定を変更することが可能になり、またgitで管理をしているためコードの差分に対してレビューができるようになります。 +
デメリットとしては、ファイルを書けないと設定ができないため属人性が生まれてしまう可能性があるということです。 +

== よくある開発事情（ソフトウェアスタック）
* 話す内容
Jenkinsを利用した開発では以下のような構成をとることが多くみられます。

* コミュニケーションツール(slack,mattermost)
* バージョン管理（GitHub、GitLabやSVN）
* ビルドツール(Gradle、Maven)
* テストツール(Junit、Spock)
* カバレッジツール(jacoco)
* 静的解析ツール(CheckStyle、FindBugs、PMD)
* メトリクス(SonarQube) etc..
* ライブラリ管理（Nexus、Artifacroty）

== ビルドパイプラインの紹介

* 話す内容
上記のような開発事例



